# This file was generated by @liquid-labs/catalyst-builder-workflow-local-make-
# node. Refer to https://npmjs.com/package/@liquid-labs/catalyst-builder-workflow-
# local-make-node for further details

#####
# build dist/npm-toolkit.js
#####

CATALYST_NPM_TOOLKIT_JS:=$(DIST)/npm-toolkit.js
CATALYST_NPM_TOOLKIT_JS_ENTRY=$(SRC)/index.js
BUILD_TARGETS+=$(CATALYST_NPM_TOOLKIT_JS)

$(CATALYST_NPM_TOOLKIT_JS): package.json $(CATALYST_ALL_NON_TEST_JS_FILES_SRC)
	JS_BUILD_TARGET=$(CATALYST_NPM_TOOLKIT_JS_ENTRY) \
	  JS_OUT=$@ \
	  $(CATALYST_ROLLUP) --config $(CATALYST_ROLLUP_CONFIG)

#####
# end dist/npm-toolkit.js
#####
