# This file was generated by @liquid-labs/catalyst-builder-workflow-local-make-
# node. Refer to https://npmjs.com/package/@liquid-labs/catalyst-builder-workflow-
# local-make-node for further details

.PRECIOUS: $(PRECIOUS_TARGETS)

build: $(BUILD_TARGETS)
.PHONY+=build

all: build
.PHONY+=all

docs: $(DOC_TARGETS)
.PHONY+=docs

lint: $(LINT_TARGETS)
lint-fix: $(LINT_FIX_TARGETS)
.PHONY+=lint lint-fix

test: $(TEST_TARGETS)
.PHONY+= test

qa: test lint
.PHONY+=qa

